# Generated by Django 4.1.7 on 2023-03-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='student-image'),
        ),
    ]
