# Generated by Django 4.1.7 on 2023-03-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_student_photo_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
