# Generated by Django 4.1.7 on 2023-03-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_student_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
