# Generated by Django 4.1.7 on 2023-03-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_student_info_approval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_info',
            old_name='photo_url',
            new_name='photo',
        ),
    ]
